function filename=id2ptrace(id)

PowerTrace={'zeros.ptrace','ammp.ptrace'	'eon.ptrace'	'gcc.ptrace'	'parser.ptrace'	'vpr.ptrace'...
'applu.ptrace'	'equake.ptrace'	'gzip.ptrace'	'perlbmk.ptrace'	'wupwise.ptrace'...
'apsi.ptrace'	'facerec.ptrace'	'lucas.ptrace'	'sixtrack.ptrace'...
'art.ptrace'	'fma3d.ptrace'	'mcf.ptrace'	'swim.ptrace'...
'bzip2.ptrace'	'galgel.ptrace'	'mesa.ptrace'	'twolf.ptrace'...
'crafty.ptrace'	'gap.ptrace'	'mgrid.ptrace'	'vortex.ptrace'};

filename= PowerTrace{id+1};

end