function filename=id2ttrace(id)

PowerTrace={'zeros.ttrace','ammp.ttrace'	'eon.ttrace'	'gcc.ttrace'	'parser.ttrace'	'vpr.ttrace'...
'applu.ttrace'	'equake.ttrace'	'gzip.ttrace'	'perlbmk.ttrace'	'wupwise.ttrace'...
'apsi.ttrace'	'facerec.ttrace'	'lucas.ttrace'	'sixtrack.ttrace'...
'art.ttrace'	'fma3d.ttrace'	'mcf.ttrace'	'swim.ttrace'...
'bzip2.ttrace'	'galgel.ttrace'	'mesa.ttrace'	'twolf.ttrace'...
'crafty.ttrace'	'gap.ttrace'	'mgrid.ttrace'	'vortex.ttrace'};

filename= PowerTrace{id+1};

end